### ISSUE TITLE
panic: runtime error: index out of range [1] with length 1

### ISSUE THREAD

**Issue by marfeljoergsen** [mwiora/NAMEinator#24]
I just downloaded this through Arch Linux and "yay -S nameinator". Then I tried to use the tool and I get:
```
trying to load nameservers from datasrc/nameserver-globals.csv
panic: runtime error: index out of range [1] with length 1
```
The full error is below, I haven't digged into the reason for this - but can see you appreciate feedback...

```
$ nameinator
starting NAMEinator - version 0.3 alpha
understood the following configuration: {numberOfDomains:100 debug:false contest:true nameserver:}
-------------
NOTE: as this is an alpha - we rely on feedback - please report bugs and featurerequests to https://github.com/mwiora/NAMEinator/issues and provide this output
OS: linux ARCH: amd64
-------------
trying to load nameservers from datasrc/nameserver-globals.csv
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.readNameserversFromFile(0xc000088b40, 0x0, 0x0, 0x0, 0x6f9f46, 0x1e)
	github.com/mwiora/nameinator/loader.go:52 +0x436
main.prepareBenchmarkNameservers(0xc000088b40, 0x0, 0x0, 0x0)
	github.com/mwiora/nameinator/loader.go:17 +0xc0
main.prepareBenchmark(0xc000088b40, 0x0, 0x0, 0x0, 0xc000088b70, 0x0, 0x0, 0x0)
	github.com/mwiora/nameinator/main.go:109 +0x42
main.main()
	github.com/mwiora/nameinator/main.go:146 +0xa1

```

**Comment by mwiora** [comment]
hey man - thanks for your feedback :D

however I think the solution would be to place the [nameserver-globals.csv](https://github.com/mwiora/NAMEinator/blob/master/datasrc/nameserver-globals.csv) and most probably the [alexa-top-2000-domains](https://github.com/mwiora/NAMEinator/blob/master/datasrc/alexa-top-2000-domains.txt) file in the folder datasrc/ (which might need to be created) - I will rework the process by providing a nameserver-list this month and trigger an update to the repository. THANKS!

I'll keep this case open until the feature is implemented, so you will be notified as soon as the update is released...

Cheers,
Matthias

**Comment by marfeljoergsen** [comment]
Thanks for the feedback. I'll be happy to test later (but could maybe take a while before a new version will be included in the arch linux AUR-repository, but if it works there, it'll work for a lot of people) :-)

Br,
Martin

**Comment by kevp58** [comment]
Hi Matthias, installed and then received this error.  I went on to create the datasrc/ directory as you mentioned.  I created it in /bin/datasrc/ and downloaded the 2 files mentioned in your previous answer - it still does not work.  
Perhaps specifying where this "datasrc" directory should be, will help?  A common directory like /etc/nameinator would suffice, and could then be used for possible future saving of a config file as well?  

Below is my nameinator output and system info:-  

**Output Info:**
> nameinator
starting NAMEinator - version 0.3 alpha
understood the following configuration: {numberOfDomains:100 debug:false contest:true nameserver:}
-------------
NOTE: as this is an alpha - we rely on feedback - please report bugs and featurerequests to https://github.com/mwiora/NAMEinator/issues and provide this output
OS: linux ARCH: amd64
-------------
trying to load nameservers from datasrc/nameserver-globals.csv
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.readNameserversFromFile(0xc000098b40, 0x0, 0x0, 0x0, 0x6fd4f8, 0x1e)
        github.com/mwiora/nameinator/loader.go:52 +0x436
main.prepareBenchmarkNameservers(0xc000098b40, 0x0, 0x0, 0x0)
        github.com/mwiora/nameinator/loader.go:17 +0xc0
main.prepareBenchmark(0xc000098b40, 0x0, 0x0, 0x0, 0xc000098b70, 0x0, 0x0, 0x0)
        github.com/mwiora/nameinator/main.go:109 +0x42
main.main()
        github.com/mwiora/nameinator/main.go:146 +0xa1
> 

**System Info:**
Kernel		: Linux 4.19.91-1-MANJARO (x86_64)
Version		: #1 SMP Sat Dec 21 11:18:44 UTC 2019
C Library		: GNU C Library / (GNU libc) 2.30
Distribution	: Manjaro Linux
Desktop		: KDE plasmashell 5.17.4

Regards
Kevin

**Comment by AndydeCleyre** [comment]
@marfeljoergsen @kevp58 

Looks like you should make the folder within the current working directory, wherever you are when you run the program.

**Comment by brent-franklin** [comment]
Just came by because I was getting this same error. I downloaded it from the AUR repository using the Yogurt AUR helper i.e. yay nameinator. 

I went to my home directory and created a directory named datasrc/, I created the files recommended by @mwiora and copied the information into the files from your github repo. I ran nameinator while in my home directory and it works for me now, thank you for the information @mwiora! Works great :+1: 

Just in case this helps, here is my system information.

-Version-
Kernel		: Linux 5.8.18-1-MANJARO (x86_64)
Version		: #1 SMP PREEMPT Sun Nov 1 14:10:04 UTC 2020
C Library		: GNU C Library / (GNU libc) 2.32
Distribution	: Manjaro Linux
Desktop           : KDE plasmashell 5.17.4

**Comment by moore-bryan** [comment]
Hello, all... I've taken the steps articulated by @mwiora and created the datasrc directory, but running nameinator from both my home dir, my "Scripts" dir in which I placed the datasrc dir, and in the datasrc dir itself all yielded no love.

Any other ideas?

```
Description:	Manjaro Linux
Release:	20.2
Codename:	Nibia
```

**Comment by artogahr** [comment]
This is to let you know it's still an issue

Details:

Arch linux, using nameinator package from AUR

```
➜ ~ nameinator          
starting NAMEinator - version custom
understood the following configuration: {numberOfDomains:100 debug:false contest:true nameserver:}
-------------
NOTE: as this is an alpha - we rely on feedback - please report bugs and featurerequests to https://github.com/mwiora/NAMEinator/issues and provide this output
OS: linux ARCH: amd64
-------------
trying to load nameservers from datasrc/nameserver-globals.csv
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.readNameserversFromFile({0xc00007cbd0, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0}}, {0x5616afe45fee?, 0x0?})
	NAMEinator/loader.go:52 +0x3c5
main.prepareBenchmarkNameservers({0xc00007cbd0, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0}})
	NAMEinator/loader.go:17 +0xec
main.prepareBenchmark({0xc00007cbd0, {{0x0, 0x0}, 0x0, 0x0, 0x0, 0x0}}, {0xc00007cc00, {{0x0, 0x0}, ...}})
	NAMEinator/main.go:126 +0x118
main.main()
	NAMEinator/main.go:164 +0x97
```
