### ISSUE TITLE
Index out of range trying to load nameservers

### ISSUE THREAD

**Issue by Zeioth** [mwiora/NAMEinator#52]
It seems to have problems to fetch the DNS list

```
╰─$ nameinator -debug                                                                                                                                                                       [2]
starting NAMEinator - version custom
understood the following configuration: {numberOfDomains:100 debug:true contest:true nameserver:}
-------------
NOTE: as this is an alpha - we rely on feedback - please report bugs and featurerequests to https://github.com/mwiora/NAMEinator/issues and provide this output
OS: linux ARCH: amd64
-------------
DEBUG: nslookup output
Server:         192.168.1.1
Address:        192.168.1.1#53

Non-authoritative answer:
*** Can't find .: No answer


DEBUG: dns server
192.168.1.1
trying to load nameservers from datasrc/nameserver-globals.csv
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
main.readNameserversFromFile(0xc000096bd0, 0x0, 0x0, 0x0, 0x55e1bf1af54a, 0x1e)
        NAMEinator/loader.go:52 +0x45f
main.prepareBenchmarkNameservers(0xc000096bd0, 0x0, 0x0, 0x0)
        NAMEinator/loader.go:17 +0xb9
main.prepareBenchmark(0xc000096bd0, 0x0, 0x0, 0x0, 0xc000096c00, 0x0, 0x0, 0x0)
        NAMEinator/main.go:126 +0x45
main.main()
        NAMEinator/main.go:164 +0xad

```

**Comment by Chaprnks** [comment]
Had the same issue. I just compiled it myself & that fixed it :)

[NAMEinator.zip](https://github.com/mwiora/NAMEinator/files/6603480/NAMEinator.zip)

**Comment by Termuellinator** [comment]
> Had the same issue. I just compiled it myself & that fixed it :)
> 
> [NAMEinator.zip](https://github.com/mwiora/NAMEinator/files/6603481/NAMEinator.zip)

did you change anything to make it work? Cause your .exe is not very useful on linux ^^

**Comment by Chaprnks** [comment]
Oh, sorry; I figured you were using Windows. I think it just needs the go project directory in it's original position to find the nameservers list (the compiled binary alone threw a file not found error). I currently have WSL (windows subsystem linux) ubuntu on my computer, so I'll give the same process a try on Linux & update you on how it goes

**Comment by Termuellinator** [comment]
it also works when you execute it with the "datasrc" folder inside the working dir - but thanks anyway :)

**Comment by Chaprnks** [comment]
> it also works when you execute it with the "datasrc" folder inside the working dir - but thanks anyway :)

I'm glad you figured it out! :)

**Comment by articuno1au** [comment]
Same cause as: https://github.com/mrwiora/NAMEinator/issues/56#issuecomment-1312380623

You can follow the steps there if you need a bit more guidance.
